### ISSUE TITLE
[0.3.0] No types visible for typescript nor typescriptreact

### ISSUE THREAD

**Issue by fbartho** [MartinJohns/vscode-inline-types#20]
I installed the latest version, and enabled it for my workspace. Our project is relatively large (maybe?), and I was getting no output from the plugin (I tested it a couple weeks ago, and it worked on a plain TS file, then).
It also appeared to hang / interfere with normal type checking.

I tested in pure `.ts` files, and in `.tsx`, and I got no output. I didn't see any errors anywhere, but I don't know where to look.

I'm happy to test more things, just let me know what information I could provide or where I could look for debug output.

```
VSCode @ Version 1.24.1 (1.24.1)
```

**Comment by MartinJohns** [comment]
The problem is the size of the project. Unfortunately there's no way to access the TypeScript compiler that is used by VSCode, so I need to create my own compiler instance and parse the source again. This takes time and adds a significant overhead. Currently this process is happening right within the VSCode extension and it's not very performant. Perhaps there's also an issue when loading your project that results in an error - the amount of different configurations and use cases is unexpectedly large.

In an upcoming version I will improve this process and split the implementation in a client and server part (opaque to the users) to improve performance. I'll also add some sort of busy-indicator and more log messages.

**Comment by fbartho** [comment]
Bummer on the VSCode sandboxing limitations. Please do tag me/this thread if there’s any proposals to the vscode core that you need me to upvote.
